### ISSUE TITLE
Problem compiling latest version

### ISSUE THREAD

**Issue by AlvaroAguilera** [expfactory/expfactory#125]
## Version of Experiment Factory:

Expfactory Version: 3.14
Docker version 19.03.5, build 633a0ea838f1
SUSE Linux Enterprise Server 12 (x86_64) Patchlevel 4

### Expected behavior

Compile and run well as it was the case until now.

### Actual behavior

Docker container crashes right after starting. Several error while building the images. Attached is the output of the docker build command.

### Steps to reproduce behavior

`docker run -v $PWD:/data vanessa/expfactory-builder build stroop n-back`

`docker build --no-cache -t expfactory/experiments .`

[docker_build.txt](https://github.com/expfactory/expfactory/files/4181790/docker_build.txt)

**Comment by vsoch** [comment]
hey @AlvaroAguilera ! I just reproduced your error - and a quick note that the containers are now released on quay.io (but we build from master so it will reproduce the same):

https://quay.io/repository/vanessa/expfactory-builder?tab=tags

What I'm seeing is that jinja2 has a syntax error, and I'm interested to see if the version is different than it was previously (perhaps they expect a higher version of Python that is not provided in the container?) Here is the error:

```
  File "<frozen importlib._bootstrap_external>", line 1096, in _legacy_get_spec
  File "<frozen importlib._bootstrap>", line 444, in spec_from_loader
  File "<frozen importlib._bootstrap_external>", line 533, in spec_from_file_location
  File "/usr/local/lib/python3.5/dist-packages/Jinja2-3.0.0a1-py3.5.egg/jinja2/bccache.py", line 207
    dirname = f"_jinja2-cache-{os.getuid()}"
                                           ^
SyntaxError: invalid syntax
[2020-02-10 16:57:16 +0000] [48] [INFO] Worker exiting (pid: 48)
[2020-02-10 16:57:16 +0000] [1] [INFO] Shutting down: Master
[2020-02-10 16:57:16 +0000] [1] [INFO] Reason: Worker failed to boot.
```

Actually, you can't even import jinja2! This is just starting a shell:

```
>>> import jinja2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/usr/local/lib/python3.5/dist-packages/Jinja2-3.0.0a1-py3.5.egg/jinja2/__init__.py", line 8, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 954, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 896, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1139, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1115, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1096, in _legacy_get_spec
  File "<frozen importlib._bootstrap>", line 444, in spec_from_loader
  File "<frozen importlib._bootstrap_external>", line 533, in spec_from_file_location
  File "/usr/local/lib/python3.5/dist-packages/Jinja2-3.0.0a1-py3.5.egg/jinja2/bccache.py", line 207
    dirname = f"_jinja2-cache-{os.getuid()}"
                                           ^
SyntaxError: invalid syntax
>>> 
```

Note that it's installing `Best match: Jinja2 3.0.0a1` and the previous version we were using appears to have been

```python
>>> jinja2.__version__
'2.10'
```

What I just tried is to install the previous version in the broken container, and that seems to fix the issue. What I'll do is prepare a branch for you with this version fixed, and then you can test it out.

**Comment by vsoch** [comment]
Here you go https://github.com/expfactory/expfactory/pull/126! Please try building and running from that branch, e.g., in your Dockerfile change:

```
RUN git clone -b master https://www.github.com/expfactory/expfactory
```
to
```
RUN git clone -b fix/wekzerg-version https://www.github.com/expfactory/expfactory
```
and let me know how it goes!

**Comment by vsoch** [comment]
@AlvaroAguilera you never responded on here from last year - is this no longer an issue for you?

**Comment by AlvaroAguilera** [comment]
Sorry that I forgot to reply. Yes, your previous comment solved the issue and I haven't had a problem since then! 

Thank you a lot!

**Comment by vsoch** [comment]
So - did you test the PR and you'd want a release? Or are you saying that the current version on master is working as it should? I was hoping you would look at the PR linked, and test it out to confirm the changes are good. Did you see the link above, and instructions for testing? Are you just working off of that branch?

**Comment by AlvaroAguilera** [comment]
This issue should be closed since I cannot reproduce the problem any longer.
