### ISSUE TITLE
It's dangerous 2.1 not working

### ISSUE THREAD

**Issue by AlvaroAguilera** [expfactory/expfactory#152]
Hello,

today we started experiencing an error when deploying Experiment Factory.

We pull the code using:

docker run --name ourexp -v /data/ourexp/exp-tasks:/data/ quay.io/vanessa/expfactory-builder build  /data/e1 /data/2

When we start the container after compilation we get the following error:

----------------------------------------------------------------------------------------------------------------------------------------------------------------

[2022-02-18 16:53:36 +0000] [29] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.8/dist-packages/expfactory-3.2.11-py3.8.egg/expfactory/wsgi.py", line 1, in <module>
    from expfactory.server import app
  File "/usr/local/lib/python3.8/dist-packages/expfactory-3.2.11-py3.8.egg/expfactory/server.py", line 27, in <module>
    from expfactory.database import *
  File "/usr/local/lib/python3.8/dist-packages/expfactory-3.2.11-py3.8.egg/expfactory/database/__init__.py", line 4, in <module>
    from .filesystem import *
  File "/usr/local/lib/python3.8/dist-packages/expfactory-3.2.11-py3.8.egg/expfactory/database/filesystem.py", line 32, in <module>
    from flask import session
  File "/usr/local/lib/python3.8/dist-packages/Flask-1.0.2-py3.8.egg/flask/__init__.py", line 21, in <module>
    from .app import Flask, Request, Response
  File "/usr/local/lib/python3.8/dist-packages/Flask-1.0.2-py3.8.egg/flask/app.py", line 25, in <module>
    from . import cli, json
  File "/usr/local/lib/python3.8/dist-packages/Flask-1.0.2-py3.8.egg/flask/json/__init__.py", line 21, in <module>
    from itsdangerous import json as _json
ImportError: cannot import name 'json' from 'itsdangerous' (/usr/local/lib/python3.8/dist-packages/itsdangerous-2.1.0-py3.8.egg/itsdangerous/__init__.py)
----------------------------------------------------------------------------------------------------------------------------------------------------------------

Apparently it can be resolved by keeping itdangerous 2.0.1 instead of  2.10.

Regards
Alvaro

**Comment by AlvaroAguilera** [comment]
Did I hit the wrong repo *again*? Isn't this docker-related? Sorry for that if it's not.

**Comment by vsoch** [comment]
haha no worries! expfactory-docker is a previous version of expfactory at expfactory.org. The v2 (with containers) is here.

I should be able to take a look at this in the evening / weekend - if you want to open a PR sooner with a fix I can review then too.

**Comment by vsoch** [comment]
okay try this test container - I updated flask to 1.4.4 instead of downgrading it's dangerous. If there are other compatibility issues / issues with running the experiment LMK! 

```bash
docker pull vanessa/expfactory-builder-dev:test-flask-1.4.4
```

**Comment by AlvaroAguilera** [comment]
I did:
`docker pull vanessa/expfactory-builder-dev:test-flask-1.4.4`

followed by:
`docker run --name mytest -v /data/mytest/exp-tasks:/data  vanessa/expfactory-builder-dev:test-flask-1.4.4 build /data/e1 /data/e2`

but I still get the same error :-/

**Comment by vsoch** [comment]
This works for me:

```
$ docker run -it vanessa/expfactory-builder-dev:test-flask-1.4.4 build stroop
Expfactory Version: 3.2.12
LOG Recipe written to /data/Dockerfile

To build, cd to directory with Dockerfile and:
              docker build -t expfactory/experiments .
```
Do you mean you tried to build the Dockerfile after?

**Comment by vsoch** [comment]
That also works for me:
```
$ docker build -t expfactory/experiments .
[+] Building 0.6s (14/14) FINISHED                                                                                                                           
 => [internal] load build definition from Dockerfile                                                                                                    0.0s
 => => transferring dockerfile: 38B                                                                                                                     0.0s
 => [internal] load .dockerignore                                                                                                                       0.0s
 => => transferring context: 2B                                                                                                                         0.0s
 => [internal] load metadata for quay.io/vanessa/expfactory-builder:base                                                                                0.5s
 => [1/9] FROM quay.io/vanessa/expfactory-builder:base@sha256:c333d47d0de43d1e322134e9d479a1a5d26e0023d5e048ae9e76c837be1ec7d8                          0.0s
 => [internal] load build context                                                                                                                       0.0s
 => => transferring context: 27.60kB                                                                                                                    0.0s
 => CACHED [2/9] WORKDIR /opt                                                                                                                           0.0s
 => CACHED [3/9] ADD . /opt                                                                                                                             0.0s
 => CACHED [4/9] WORKDIR /opt/expfactory                                                                                                                0.0s
 => CACHED [5/9] RUN python3 setup.py install                                                                                                           0.0s
 => CACHED [6/9] RUN mv /opt/entrypoint.sh /entrypoint.sh                                                                                               0.0s
 => CACHED [7/9] RUN chmod u+x /entrypoint.sh                                                                                                           0.0s
 => CACHED [8/9] RUN mkdir -p /scif/apps                                                                                                                0.0s
 => CACHED [9/9] RUN mkdir -p /data                                                                                                                     0.0s
 => exporting to image                                                                                                                                  0.0s
 => => exporting layers                                                                                                                                 0.0s
 => => writing image sha256:47dc81689ba3e03fd524223ec3919d9974f3f48c0d1b8b72a113e119c9aac1f6                                                            0.0s
 => => naming to docker.io/expfactory/experiments                                                         
```

**Comment by vsoch** [comment]
I basically need a way to reproduce what you are seeing!

**Comment by AlvaroAguilera** [comment]
Compiling is not a problem. That works fine. 

When I start the container with (simplified)
`docker run  expfactory/experiments --experiments e1,e2  --headless --no-randomize start`

It doesn't start. That's where I get the error I posted before.

**Comment by vsoch** [comment]
okay reproduced! ty!

**Comment by vsoch** [comment]
okay so two issues - the FROM image in the generated dockerfile needs to be updated, and then when that happens markupsafe needs to be pinned. so:

1. re pull that same dev container
2. build with --no-cache this recipe

```
FROM vanessa/expfactory-builder-dev:test-flask-1.4.4

########################################
# Configure
########################################

ENV EXPFACTORY_STUDY_ID expfactory
ENV EXPFACTORY_SERVER localhost
ENV EXPFACTORY_CONTAINER true
ENV EXPFACTORY_DATA /scif/data
ENV EXPFACTORY_DATABASE filesystem
ENV EXPFACTORY_HEADLESS false
ENV EXPFACTORY_BASE /scif/apps
 
ADD startscript.sh /startscript.sh
RUN chmod u+x /startscript.sh

RUN apt-get update && apt-get install -y nginx git python3-pip python3-dev
WORKDIR /opt 
WORKDIR expfactory
RUN cp script/nginx.gunicorn.conf /etc/nginx/sites-enabled/default && \
    cp script/nginx.conf /etc/nginx/nginx.conf
RUN mkdir -p /scif/data # saved data
RUN mkdir -p /scif/apps # experiments 
RUN mkdir -p /scif/logs # gunicorn logs 
RUN python3 -m pip install gunicorn
RUN cp expfactory/config_dummy.py expfactory/config.py && \
    chmod u+x /opt/expfactory/script/generate_key.sh && \
    /bin/bash /opt/expfactory/script/generate_key.sh /opt/expfactory/expfactory/config.py
RUN python3 setup.py install
RUN python3 -m pip install pyaml    pymysql psycopg2-binary
RUN apt-get clean          # tests, mysql,  postgres

########################################
# Experiments
########################################


LABEL EXPERIMENT_stroop /scif/apps/stroop
WORKDIR /scif/apps
RUN expfactory install https://github.com/expfactory-experiments/stroop



ENTRYPOINT ["/bin/bash", "/startscript.sh"]
EXPOSE 5000
EXPOSE 80
```

**Comment by AlvaroAguilera** [comment]
Thank you, Vanessa. You are too kind for this world.

**Comment by vsoch** [comment]
Let me know if that fixed it, I'll get an official PR in tonight.

**Comment by AlvaroAguilera** [comment]
Yes, that fixed the problem.

**Comment by vsoch** [comment]
@AlvaroAguilera this is merged please give a run to see if it's fixed on your end! https://quay.io/repository/vanessa/expfactory-builder?tab=tags

**Comment by AlvaroAguilera** [comment]
I'm not sure how exactly you want me to try it. The old build command isn't working yet:

docker run --name build_myexp -v /data/myexp/exp-tasks:/data/   quay.io/repository/vanessa/expfactory-builder build /data/myexp

I still have to use vanessa/expfactory-builder-dev:test-flask-1.4.4

**Comment by vsoch** [comment]
Did you pull the new image and build with no cache?

**Comment by AlvaroAguilera** [comment]
I did

`docker pull vanessa/expfactory-builder-dev:latest`

and built w/o cache

**Comment by vsoch** [comment]
I can't reproduce @AlvaroAguilera - here is what I did. I'll need to be able to reproduce what you are seeing to confirm there is an issue and work on it again.

```bash
$ docker pull quay.io/vanessa/expfactory-builder
Using default tag: latest
latest: Pulling from vanessa/expfactory-builder
08c01a0ec47e: Already exists 
de745faad3bb: Pull complete 
b64dde8eca2e: Pull complete 
b03b77aa2ef2: Pull complete 
3128a87f5daa: Pull complete 
5ec3dcf31ffc: Pull complete 
34aa17a75a1e: Pull complete 
fc4e60131a9f: Pull complete 
b06beeba132c: Pull complete 
Digest: sha256:8b37738f8f827075cee3ea76e83286f56443863b6e07f502da4d479a1b7000f4
Status: Downloaded newer image for quay.io/vanessa/expfactory-builder:latest
quay.io/vanessa/expfactory-builder:latest
```
Now go to /tmp/data and make sure previous files are removed.

```bash
$ cd /tmp/data/
$ ls
Dockerfile  startscript.sh
$ rm startscript.sh 
rm: remove write-protected regular file 'startscript.sh'? yes
$ sudo rm Dockerfile 
 ls
$ docker run -it -v $PWD:/data quay.io/vanessa/expfactory-builder build stroop
Expfactory Version: 3.2.12
LOG Recipe written to /data/Dockerfile

To build, cd to directory with Dockerfile and:
              docker build --no-cache -t expfactory/experiments .
```
Build the container
```bash
$ docker build --no-cache -t expfactory/experiments .
[+] Building 39.1s (22/22) FINISHED                                                                                                                     
 => [internal] load build definition from Dockerfile                                                                                               0.0s
 => => transferring dockerfile: 1.49kB                                                                                                             0.0s
 => [internal] load .dockerignore                                                                                                                  0.0s
 => => transferring context: 2B                                                                                                                    0.0s
 => [internal] load metadata for quay.io/vanessa/expfactory-builder:base                                                                           0.0s
 => [internal] load build context                                                                                                                  0.0s
 => => transferring context: 5.34kB                                                                                                                0.0s
 => CACHED [ 1/17] FROM quay.io/vanessa/expfactory-builder:base                                                                                    0.0s
 => [ 2/17] ADD startscript.sh /startscript.sh                                                                                                     0.0s
 => [ 3/17] RUN chmod u+x /startscript.sh                                                                                                          0.3s
 => [ 4/17] WORKDIR /opt                                                                                                                           0.0s
 => [ 5/17] RUN git clone -b master https://github.com/expfactory/expfactory                                                                       6.7s
 => [ 6/17] WORKDIR expfactory                                                                                                                     0.0s 
 => [ 7/17] RUN cp script/nginx.gunicorn.conf /etc/nginx/sites-enabled/default &&     cp script/nginx.conf /etc/nginx/nginx.conf                   0.5s
 => [ 8/17] RUN mkdir -p /scif/data # saved data                                                                                                   0.4s
 => [ 9/17] RUN mkdir -p /scif/apps # experiments                                                                                                  0.3s
 => [10/17] RUN mkdir -p /scif/logs # gunicorn logs                                                                                                0.3s
 => [11/17] RUN python3 -m pip install gunicorn                                                                                                    1.6s
 => [12/17] RUN cp expfactory/config_dummy.py expfactory/config.py &&     chmod u+x /opt/expfactory/script/generate_key.sh &&     /bin/bash /opt/  0.4s
 => [13/17] RUN python3 setup.py install                                                                                                          17.1s 
 => [14/17] RUN python3 -m pip install pyaml    pymysql psycopg2-binary                                                                            3.4s 
 => [15/17] RUN apt-get clean          # tests, mysql,  postgres                                                                                   0.4s 
 => [16/17] WORKDIR /scif/apps                                                                                                                     0.0s
 => [17/17] RUN expfactory install https://github.com/expfactory-experiments/stroop                                                                7.2s
 => exporting to image                                                                                                                             0.2s
 => => exporting layers                                                                                                                            0.2s
 => => writing image sha256:db96ac36ecbeeb49a7f21cfdeebf7b27a814f81be448964d823b2efc5f7c23b9                                                       0.0s
 => => naming to docker.io/expfactory/experiments                                                                                                  0.0s
```
Run the container:
```bash
$ docker run -it expfactory/experiments start
Database set as filesystem
Starting Web Server

 * Starting nginx nginx                                                                                                                          [ OK ] 
==> /scif/logs/gunicorn-access.log <==

==> /scif/logs/gunicorn.log <==
[2022-02-21 17:18:11 +0000] [1] [INFO] Starting gunicorn 20.1.0
[2022-02-21 17:18:11 +0000] [1] [INFO] Listening at: http://0.0.0.0:5000 (1)
[2022-02-21 17:18:11 +0000] [1] [INFO] Using worker: sync
[2022-02-21 17:18:11 +0000] [40] [INFO] Booting worker with pid: 40
Found 1 valid experiments
WARNING No user experiments selected, providing all 1
LOG Headless mode: False
LOG User has selected: []
LOG Experiments Available: /scif/apps/stroop
LOG Randomize: True
LOG Final Set 
stroop
DATABASE: filesystem
LOG Data base: /scif/data/expfactory
```
I don't see an errors - here is the Dockerfile for you to compare:

```bash
FROM quay.io/vanessa/expfactory-builder:base

########################################
# Configure
########################################

ENV EXPFACTORY_STUDY_ID expfactory
ENV EXPFACTORY_SERVER localhost
ENV EXPFACTORY_CONTAINER true
ENV EXPFACTORY_DATA /scif/data
ENV EXPFACTORY_DATABASE filesystem
ENV EXPFACTORY_HEADLESS false
ENV EXPFACTORY_BASE /scif/apps
 
ADD startscript.sh /startscript.sh
RUN chmod u+x /startscript.sh

WORKDIR /opt 
RUN git clone -b master https://github.com/expfactory/expfactory
WORKDIR expfactory 
RUN cp script/nginx.gunicorn.conf /etc/nginx/sites-enabled/default && \
    cp script/nginx.conf /etc/nginx/nginx.conf
RUN mkdir -p /scif/data # saved data
RUN mkdir -p /scif/apps # experiments 
RUN mkdir -p /scif/logs # gunicorn logs 
RUN python3 -m pip install gunicorn
RUN cp expfactory/config_dummy.py expfactory/config.py && \
    chmod u+x /opt/expfactory/script/generate_key.sh && \
    /bin/bash /opt/expfactory/script/generate_key.sh /opt/expfactory/expfactory/config.py
RUN python3 setup.py install
RUN python3 -m pip install pyaml    pymysql psycopg2-binary
RUN apt-get clean          # tests, mysql,  postgres

########################################
# Experiments
########################################


LABEL EXPERIMENT_stroop /scif/apps/stroop
WORKDIR /scif/apps
RUN expfactory install https://github.com/expfactory-experiments/stroop



ENTRYPOINT ["/bin/bash", "/startscript.sh"]
EXPOSE 5000
EXPOSE 80
```
Perhaps you need to repull `quay.io/vanessa/expfactory-builder:base` too? I purge my containers recently so I did. We can also shell into the container and verify the changes for the fix (the version of Flask and markdownsafe are correct):

```
# pip freeze | grep Flask
Flask==1.1.4
# pip freeze | grep Markup
MarkupSafe==2.0.1
```
So please go carefully through your steps and do some sanity checks, and if there is still an issue please give me enough to reproduce it.

**Comment by AlvaroAguilera** [comment]
Now it seems to work fine. Thanks again.
