### ISSUE TITLE
Fatal error with `expfactory users --finish` 

### ISSUE THREAD

**Issue by earcanal** [expfactory/expfactory#48]
I don't know how to delete user tokens so I tried `--finish`.

```
root@26238e416067:/scif/apps# expfactory users --finish 
usage: expfactory users [-h] [--database {fllesystem,sqlite}] [--new NEW]
                        [--list] [--revoke REVOKE] [--refresh REFRESH]
                        [--restart RESTART] [--finish FINISH]
expfactory users: error: argument --finish: expected one argument
root@26238e416067:/scif/apps# expfactory users --finish 0d1d1886-c2c5-46d1-829f-5712684852ed
Traceback (most recent call last):
  File "/usr/local/bin/expfactory", line 9, in <module>
    load_entry_point('expfactory==3.1', 'console_scripts', 'expfactory')()
  File "/usr/local/lib/python3.5/dist-packages/expfactory-3.1-py3.5.egg/expfactory/cli/__init__.py", line 237, in main
    subparser=subparser)
  File "/usr/local/lib/python3.5/dist-packages/expfactory-3.1-py3.5.egg/expfactory/cli/users.py", line 89, in main
    print("[%s] %s not successful. See logs for details." %(action.lower()))
TypeError: not enough arguments for format string
```

**Comment by vsoch** [comment]
that looks like a bug! You have the flow correct - you would manually finish a user with --finish, and this just corresponds to renaming the folder on the filesystem. Let me see if I can fix that bug.

**Comment by vsoch** [comment]
This is also fixed.
